output * mode 1920x1080 transform 90
seat seat0 fallback true
focus_follows_mouse no
for_window [app_id="^k230.card."] card_shell ordinary, floating enable, border none, resize set 100 ppt 100 ppt, move position 0 0
