#!/usr/bin/env python3
"""Write a repeatable source-boundary audit for the card-composition route."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path


def run(*args: str, cwd: Path) -> str:
    return subprocess.run(args, cwd=cwd, check=True, text=True,
                          stdout=subprocess.PIPE).stdout.strip()


def derivation_source(flake: str, cwd: Path) -> tuple[str, str, str]:
    derivations = run("nix", "path-info", "--derivation", f"{flake}#shell-compositor",
                      f"{flake}#touch-launcher", cwd=cwd).splitlines()
    if len(derivations) != 2:
        raise RuntimeError("expected derivations for shell-compositor and touch-launcher")
    records = []
    for derivation in derivations:
        data = json.loads(run("nix", "derivation", "show", derivation, cwd=cwd))
        records.append((derivation, next(iter(data["derivations"].values()))))
    wrapper_drv, wrapper_record = next(
        (derivation, record) for derivation, record in records
        if record["env"].get("pname") == "sway")
    launcher_drv = next(derivation for derivation, record in records
                        if derivation != wrapper_drv)
    unwrapped_output = next(path for path in wrapper_record["env"]["paths"].split()
                            if "sway-unwrapped" in path)
    unwrapped_drv = run("nix", "path-info", "--derivation", unwrapped_output,
                        cwd=cwd)
    data = json.loads(run("nix", "derivation", "show", unwrapped_drv, cwd=cwd))
    shell_record = next(iter(data["derivations"].values()))
    shell_drv = unwrapped_drv
    source = shell_record["env"]["src"]
    return shell_drv, launcher_drv, source


def require(path: Path, *needles: str) -> None:
    text = path.read_text()
    absent = [needle for needle in needles if needle not in text]
    if absent:
        raise RuntimeError(f"{path}: missing source markers: {', '.join(absent)}")


def audit(sway_source: Path, repo: Path) -> None:
    require(repo / "nix/touch-launcher/touch-launcher.c",
            "zwlr_layer_shell_v1", "wl_seat_get_touch", "wl_shm")
    require(sway_source / "sway/tree/view.c",
            "view->scene_tree", "view_close", "wlr_scene_node_set_position")
    require(sway_source / "sway/input/seat.c",
            "seatop_touch_motion", "seat_set_focus_container")
    require(sway_source / "sway/input/seatop_default.c",
            "seatop_begin_down")


def report(shell_drv: str, launcher_drv: str, sway_source: Path) -> str:
    return f"""# Card-composition pinned source audit

Generated by `python3 tools/audit-card-composition-sources.py --flake . --output docs/research/card-composition-source-audit.md`.

## Resolved inputs

* `.#shell-compositor` derivation: `{shell_drv}`
* `.#touch-launcher` derivation: `{launcher_drv}`
* Sway 1.12 source from the compositor derivation's `src` environment field: `{sway_source}`
* Installed wlroots headers: `/nix/store/dsxkjg3whpq9xvy5kd5k7mddq927a2l6-wlroots-0.20.2/include/wlroots-0.20`.

The resolved package is the same flake attribute used by the `k230` NixOS
configuration. This audit does not infer an ABI from a host Sway executable.

## Client/protocol boundary

`nix/touch-launcher/default.nix:13-20` generates only layer-shell and
xdg-shell client protocols and links `wayland-client`. In
`nix/touch-launcher/touch-launcher.c:68-75,765-789`, the launcher binds
`wl_compositor`, `wl_shm`, `wl_seat`, and `zwlr_layer_shell_v1`, creates its
own overlay surface, and requests non-interactive keyboard focus. Its
`wl_touch` listener (`:723-761`) receives touch only after Sway has selected
that client surface. It has neither a compositor-owned `wlr_surface` reference
for another client nor a global pre-routing touch hook. The current client
route can therefore retain metadata/launcher controls but cannot produce live
application cards, global drag, or authoritative focus restoration.

## Sway/wlroots boundary

The pinned Sway source allocates a `scene_tree` and `content_tree` per
`sway_view` in `sway/tree/view.c:77-95`, assigns the view scene descriptor at
`:85`, and positions content through `wlr_scene_node_set_position` at
`:1043-1047`. It destroys the scene node during view teardown at `:135-139`.
It already keeps a saved-surface tree and clones scene-buffer references at
`:1245-1289`; this is evidence of a compositor-owned lifetime boundary, not a
license to expose client buffers to another process.

Sway routes touch through seat operations: `sway/input/seat.c:1577-1600`
dispatches down/motion/up/cancel to the active `seatop_impl`, and the default
operation resolves a container then calls `seat_set_focus_container` and
`seatop_begin_down` in `sway/input/seatop_default.c:242-271`. Focus helpers
are in `sway/input/seat.c:1255-1299`; `view_close` dispatches the existing
view implementation at `sway/tree/view.c:547-551`. These are patch points for
an opt-in Sway-owned card state machine.

wlroots 0.20's installed `wlr/types/wlr_scene.h:306-351,708-715` exposes node
positioning, input hit-testing, and an XDG-surface scene subtree. It has no
transform for a whole scene subtree: `wlr_scene_buffer_set_dest_size` at
`:535-543` scales an individual buffer only. Sway's existing
`view_save_buffer` at `sway/tree/view.c:1245-1289` clones scene-buffer
references and disables live content, so it is a lifetime example but not a
live-card transform. The selected probe must prove identical scale and
translated coordinates for every live content/subsurface buffer across commits,
or stop without calling cropped or static output a card.

Pinned Sway also exposes more protocols than the current launcher binds:
`sway/server.c:469-476` creates foreign-toplevel managers, `:502-517` creates
export-dmabuf/screencopy/image-copy managers, and `:555-563` creates
foreign-toplevel image-capture sources. A request is served from a separate
`view->image_capture_scene` using Sway's allocator and renderer (`:230-242`),
not by sharing the live scene node. A client could enumerate/activate/close and
receive copied images, but would compose copies in its overlay, would not own
Sway's focus or pre-routing touch, and has no demonstrated frame/presentation
synchronization with copied content. That route cannot meet the coherent live
surface/global drag/focus contract at an unmeasured Pixman cost.

Its
`wlr/types/wlr_presentation_time.h:64-106` says a compositor must record
sampling/texturing and send presentation feedback only when it has that
evidence. The probe must log those calls separately from a frame callback.

## Result

The source evidence selects a narrow, opt-in Sway patch for the next probe
because it can keep app surfaces, input, focus, close dispatch, and
presentation accounting under one owner. It does **not** prove coherent live
subtree scaling, board operation, or product card UX. Those remain strict
selected-route probe gates.
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--flake", default=".")
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--sway-source", type=Path,
                        help="test-only replacement for resolving the Sway derivation")
    args = parser.parse_args()
    repo = Path.cwd()
    if args.sway_source:
        shell_drv, launcher_drv, source = "TEST-shell-compositor.drv", "TEST-touch-launcher.drv", str(args.sway_source)
    else:
        shell_drv, launcher_drv, source = derivation_source(args.flake, repo)
    sway_source = Path(source)
    audit(sway_source, repo)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report(shell_drv, launcher_drv, sway_source))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
